config/routes.rb
Cuiler::Application.routes.draw do
  root "homes#show"

  resources :admins, only: [:new, :create]
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new
    @admin = User.new
  end

  def create
    @admin = admin_from_params
    if @admin.save
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  private

  def admin_from_params
    user_params = params[:user] || Hash.new
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.admin = true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/new.html.erb
<div id='clearance' class='sign-up'>
  <h2><%= t('.title') %></h2>

  <%= form_for @admin, url: admins_path do |form| %>
    <%= render :partial => '/users/form', :object => form %>

    <div class='submit-field'>
      <%= form.submit %>
    </div>

    <div class='other-links'>
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/homes/show.html.erb
Home Page!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cuiler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <% if signed_in? %>
    Signed in as: <%= current_user.email %>
    <%= link_to 'Sign out', sign_out_path, :method => :delete %>
  <% else %>
    <%= link_to 'Sign in', sign_in_path %>
  <% end %>

  <div id="flash">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>

<%= yield %>

</body>
</html>